/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz_Socio;

import Code.Gym;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author alejandrobenitotrujillo
 */
public class VentanaSocio extends javax.swing.JFrame {

    /**
     * Creates new form Empleado_interfaz
     */
    public VentanaSocio() {
        initComponents();
        try {
            Gym.cargarActividades();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Ha ocurrido un error con la carga de actividades colectivas","ERROR", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        opcionesCuota = new javax.swing.JButton();
        misActividades = new javax.swing.JButton();
        misRegistros = new javax.swing.JButton();
        areaPersonal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        setIconImage(new ImageIcon("src/main/java/imagenes/logo.png").getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(33, 45, 62));

        opcionesCuota.setIcon(new ImageIcon("src/main/java/imagenes/opciones_de_cuota_normal.png"));
        opcionesCuota.setPressedIcon(new ImageIcon("src/main/java/imagenes/opciones_de_cuota_pequeno.png"));
        opcionesCuota.setRolloverIcon(new ImageIcon("src/main/java/imagenes/opciones_de_cuota_grande.png"));
        opcionesCuota.setBorderPainted(false);
        opcionesCuota.setContentAreaFilled(false);
        opcionesCuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesCuotaActionPerformed(evt);
            }
        });

        misActividades.setIcon(new ImageIcon("src/main/java/imagenes/actividades_normal.png"));
        misActividades.setPressedIcon(new ImageIcon("src/main/java/imagenes/actividades_pequeno.png"));
        misActividades.setRolloverIcon(new ImageIcon("src/main/java/imagenes/actividades_grande.png"));
        misActividades.setBorderPainted(false);
        misActividades.setContentAreaFilled(false);
        misActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                misActividadesActionPerformed(evt);
            }
        });

        misRegistros.setIcon(new ImageIcon("src/main/java/imagenes/mis_registros_normal.png"));
        misRegistros.setPressedIcon(new ImageIcon("src/main/java/imagenes/mis_registros_pequeno.png"));
        misRegistros.setRolloverIcon(new ImageIcon("src/main/java/imagenes/mis_registros_grande.png"));
        misRegistros.setBorderPainted(false);
        misRegistros.setContentAreaFilled(false);
        misRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                misRegistrosActionPerformed(evt);
            }
        });

        areaPersonal.setIcon(new ImageIcon("src/main/java/imagenes/area_de_personal_normal.png"));
        areaPersonal.setPressedIcon(new ImageIcon("src/main/java/imagenes/area_de_personal_peque.png"));
        areaPersonal.setRolloverIcon(new ImageIcon("src/main/java/imagenes/area_de_personal_grande.png"));
        areaPersonal.setBorderPainted(false);
        areaPersonal.setContentAreaFilled(false);
        areaPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaPersonalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione la acción que desea realizar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(misActividades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(opcionesCuota, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(misRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(areaPersonal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 105, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(opcionesCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(misActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(misRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(areaPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void opcionesCuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesCuotaActionPerformed
        // TODO add your handling code here:
        Opciones_cuota oc = new Opciones_cuota();
        oc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_opcionesCuotaActionPerformed

    private void misActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_misActividadesActionPerformed
        // TODO add your handling code here:
        Actividades ma = new Actividades();
        ma.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_misActividadesActionPerformed

    private void areaPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaPersonalActionPerformed
        // TODO add your handling code here:
        Area_de_personal ap = new Area_de_personal();
        ap.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_areaPersonalActionPerformed

    private void misRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_misRegistrosActionPerformed
        // TODO add your handling code here:
        Registros_Socio rs = new Registros_Socio();
        rs.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_misRegistrosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton areaPersonal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton misActividades;
    private javax.swing.JButton misRegistros;
    private javax.swing.JButton opcionesCuota;
    // End of variables declaration//GEN-END:variables

    private void setColour(Color BLUE) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
